packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  # 核心框架 (Core Framework)
  react: ^19.2.1
  'react-dom': ^19.2.1
  next: ^16.1.1

  # 开发工具 (Development Tools)
  typescript: ^5.9.3
  eslint: ^9.39.1
  '@eslint/eslintrc': ^3.3.1
  '@eslint/js': ^9.39.1
  '@typescript-eslint/eslint-plugin': ^8.39.0
  '@typescript-eslint/parser': ^8.39.0
  'eslint-config-next': ^15.4.5
  'eslint-config-prettier': ^9.1.2
  'eslint-plugin-only-warn': ^1.1.0
  'eslint-plugin-tailwindcss': ^3.18.2
  'eslint-plugin-turbo': ^2.5.5
  'prettier-plugin-tailwindcss': ^0.7.2
  'typescript-eslint': ^8.39.0

  # 类型定义 (Type Definitions)
  '@types/node': ^20.19.25
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3

  # UI 组件库 (UI Libraries)
  '@radix-ui/react-slot': ^1.2.3
  'lucide-react': ^0.475.0
  'next-themes': ^0.4.6

  # 样式工具 (Styling Tools)
  tailwindcss: ^3.4.17
  autoprefixer: ^10.4.20
  'tailwind-merge': ^3.3.1

  # 构建工具 (Build Tools)
  turbo: ^2.7.4
  '@turbo/gen': ^2.5.5
  prettier: ^3.7.4

  # 工具库 (Utility Libraries)
  zod: ^3.25.76
  'class-variance-authority': ^0.7.1
  clsx: ^2.1.1
  globals: ^15.15.0
  'tw-animate-css': ^1.3.6

catalogMode: prefer
